 // Images migrated to Cloudinary - local imports removed

const products = [
  // 🌿 PODI
  {
    _id: "1",
    name: "Murungai Idly/Rice Podi",
    category: "Podi",
    price: 40,
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price50Num: 40,
    price100Num: 60,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159411/FoodNex/Images/products/lbgdab7pbqn4yeuywv9x.png" }],
    description: "Nutritious moringa powder for idly and rice, packed with vitamins and minerals.",
  },
  {
    _id: "2",
    name: "Karuvepillai Idly/Rice Podi",
    category: "Podi",
    price: 40,
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price50Num: 40,
    price100Num: 60,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159419/FoodNex/Images/products/hl4ef47cjmocu9yvtrit.png" }],
    description: "Aromatic curry leaf powder perfect for enhancing the flavor of your dishes.",
  },
  {
    _id: "3",
    name: "Sambar Podi",
    category: "Podi",
    price: 40,
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price50Num: 40,
    price100Num: 60,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159420/FoodNex/Images/products/dd42iranvayztkvjpbec.png" }],
    description: "Traditional sambar powder for authentic South Indian sambar.",
  },

  // 🍚 RICE MIX
  {
    _id: "4",
    name: "Seerukeerai Rice Mix",
    category: "Rice Mix",
    price: 65,
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price50Num: 65,
    price100Num: 110,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159421/FoodNex/Images/products/zmjymi8nnku5ecxlaqb4.png" }],
    description: "Healthy spinach rice mix for a nutritious meal.",
  },
  {
    _id: "5",
    name: "Poondu Rice Mix",
    category: "Rice Mix",
    price: 50,
    price50: "₹50 (50 gms)",
    price100: "₹100 (100 gms)",
    price50Num: 50,
    price100Num: 100,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159409/FoodNex/Images/products/kx0rcjkzljnj8byo1pnp.png" }],
    description: "Garlic-infused rice mix for a flavorful twist.",
  },
  {
    _id: "6",
    name: "Paruppu Rice Mix",
    category: "Rice Mix",
    price: 50,
    price50: "₹50 (50 gms)",
    price100: "₹80 (100 gms)",
    price50Num: 50,
    price100Num: 80,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159415/FoodNex/Images/products/enn5vepmydmtdbbphnpk.png" }],
    description: "Dal rice mix for a protein-rich meal.",
  },
  {
    _id: "7",
    name: "Perandai Rice Mix",
    category: "Rice Mix",
    price: 60,
    price50: "₹60 (50 gms)",
    price100: "₹110 (100 gms)",
    price50Num: 60,
    price100Num: 110,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159416/FoodNex/Images/products/vvc1fi3pyrta34arioq8.png" }],
    description: "Medicinal veldt grape rice mix for health benefits.",
  },
  {
    _id: "8",
    name: "Nellikai Rice Mix",
    category: "Rice Mix",
    price: 65,
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price50Num: 65,
    price100Num: 110,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159413/FoodNex/Images/products/oo6t9ncorhep7dj612tr.png" }],
    description: "Gooseberry rice mix for antioxidant-rich meals.",
  },

  // 🍵 SOUP MIX
  {
    _id: "9",
    name: "Murungai Soup Mix (16 Soups)",
    category: "Soup Mix",
    price: 85,
    price50: "₹85 (16 Soups)",
    price100: null,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159412/FoodNex/Images/products/vzdt2kqwciqiisf3gyre.png" }],
    description: "Moringa soup mix for 16 servings of nutritious soup.",
  },
  {
    _id: "10",
    name: "Nellikai Soup Mix (13 Soups)",
    category: "Soup Mix",
    price: 85,
    price50: "₹85 (13 Soups)",
    price100: null,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159414/FoodNex/Images/products/dpzhd0chniquj5jreqzy.png" }],
    description: "Gooseberry soup mix for 13 servings of healthy soup.",
  },
  {
    _id: "11",
    name: "Banana Stem Soup Mix (13 Soups)",
    category: "Soup Mix",
    price: 85,
    price50: "₹85 (13 Soups)",
    price100: null,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159408/FoodNex/Images/products/mlwzpbhf54dqztxh1h0r.png" }],
    description: "Banana stem soup mix for 13 servings of detoxifying soup.",
  },
  {
    _id: "12",
    name: "Avaram Poo Soup Mix (16 Soups)",
    category: "Soup Mix",
    price: 110,
    price50: "₹110 (16 Soups)",
    price100: null,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159406/FoodNex/Images/products/avp2vuukif17dli49usw.png" }],
    description: "Neem flower soup mix for 16 servings of medicinal soup.",
  },

  // 🌼 POWDER
  {
    _id: "13",
    name: "Pure Nellikai Powder",
    category: "Powder",
    price: 65,
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price50Num: 65,
    price100Num: 110,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159420/FoodNex/Images/products/karvuo2igtegloqu94wx.png" }],
    description: "Pure gooseberry powder for health and wellness.",
  },
  {
    _id: "14",
    name: "Pure Avaram Poo Powder",
    category: "Powder",
    price: 90,
    price50: "₹90 (50 gms)",
    price100: "₹170 (100 gms)",
    price50Num: 90,
    price100Num: 170,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159418/FoodNex/Images/products/jmopjrvhffcdqtkwodta.png" }],
    description: "Pure neem flower powder for medicinal uses.",
  },
  {
    _id: "15",
    name: "Pure Karuvepillai Powder",
    category: "Powder",
    price: 50,
    price50: "₹50 (50 gms)",
    price100: "₹100 (100 gms)",
    price50Num: 50,
    price100Num: 100,
    stock: true,
    images: [{ url: "https://res.cloudinary.com/dal84gvkm/image/upload/v1774159410/FoodNex/Images/products/jqjgfqduj0lt322dgacn.png" }],
    description: "Pure curry leaf powder for culinary and health benefits.",
  },
];

export default products;
